{% set version = "0.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-superpower
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Superpower_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Superpower/Superpower_{{ version }}.tar.gz
  sha256: 6e26c4fbf586930371d724d5bbae2cdfb44f51cd832030323c15364e026db372

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-hmisc
    - r-mass
    - r-afex
    - r-dplyr
    - r-emmeans
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-mvtnorm
    - r-reshape2
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-hmisc
    - r-mass
    - r-afex
    - r-dplyr
    - r-emmeans
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-mvtnorm
    - r-reshape2
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('Superpower')"           # [not win]
    - "\"%R%\" -e \"library('Superpower')\""  # [win]

about:
  home: https://aaroncaldwell.us/SuperpowerBook/
  license: MIT
  summary: Functions to perform simulations of ANOVA designs of up to three factors. Calculates the observed power and average observed effect size for all main effects and interactions in the ANOVA, and all simple comparisons between conditions. Includes functions for analytic power calculations and additional helper functions
    that compute effect sizes for ANOVA designs, observed error rates in the simulations, and functions to plot power curves. Please see Lakens, D., & Caldwell, A. R. (2021). "Simulation-Based Power Analysis for Factorial Analysis of Variance Designs". <doi:10.1177/2515245920951503>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
